# Generated by Django 4.1.1 on 2022-09-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuqes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='point',
            options={'ordering': ['pub_date', 'title'], 'verbose_name': 'Цель', 'verbose_name_plural': 'Цели'},
        ),
        migrations.AlterField(
            model_name='point',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
