# Generated by Django 4.1.1 on 2022-09-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuqes', '0002_alter_point_options_alter_point_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
