# Generated by Django 4.1.1 on 2022-09-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuqes', '0003_point_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
