# Generated by Django 4.1.1 on 2022-09-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuqes', '0007_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(blank=True, max_length=200, verbose_name='Комментарий'),
        ),
    ]
