# Generated by Django 4.1.1 on 2022-09-29 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vuqes', '0008_alter_comment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ident',
            field=models.TextField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='point',
            name='comments',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='vuqes.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(blank=True, max_length=200, verbose_name='Оставить комментарий'),
        ),
    ]
