# Generated by Django 4.1.1 on 2022-09-29 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vuqes', '0011_alter_comment_ident_alter_point_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='comments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vuqes.comment'),
        ),
    ]
