# Generated by Django 4.1.1 on 2022-10-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuqes', '0014_comment_ident_alter_comment_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='WriteToTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=200, verbose_name='Фамилия')),
                ('phone_number', models.CharField(blank=True, max_length=200, verbose_name='Номер телефона ')),
                ('datetime', models.DateTimeField(verbose_name='Дата записи')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=200, verbose_name='Оставить комментарий '),
        ),
    ]
