# Generated by Django 4.1.1 on 2022-10-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuqes', '0016_alter_add_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbautModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
